# Generated by Django 6.0.3 on 2026-04-01 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目代碼')),
                ('name', models.CharField(max_length=100, verbose_name='科目名稱')),
                ('category', models.CharField(choices=[('asset', '資產'), ('liability', '負債'), ('equity', '投入'), ('revenue', '收入'), ('expense', '營業費用')], max_length=20, verbose_name='類別')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '會計科目',
                'verbose_name_plural': '會計科目',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=30, unique=True, verbose_name='傳票編號')),
                ('date', models.DateField(verbose_name='日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('is_system_generated', models.BooleanField(default=False, verbose_name='系統自動產生')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '傳票',
                'verbose_name_plural': '傳票',
                'ordering': ['-date', '-voucher_number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='訂單編號')),
                ('customer_name', models.CharField(max_length=200, verbose_name='客戶名稱')),
                ('order_date', models.DateField(verbose_name='訂單日期')),
                ('status', models.CharField(choices=[('pending', '待出貨'), ('shipped', '已出貨'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='狀態')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='總金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-order_date', '-order_number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU 編號')),
                ('unit', models.CharField(default='個', max_length=20, verbose_name='單位')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='目前售價')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='採購單號')),
                ('supplier', models.CharField(max_length=200, verbose_name='供應商')),
                ('date', models.DateField(verbose_name='日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已確認'), ('received', '已到貨'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '採購單',
                'verbose_name_plural': '採購單',
                'ordering': ['-date', '-order_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='借方金額')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='貸方金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_items', to='api.accountsubject', verbose_name='會計科目')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.journalvoucher', verbose_name='傳票')),
            ],
            options={
                'verbose_name': '傳票明細',
                'verbose_name_plural': '傳票明細',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='售價')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='訂單')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單明細',
                'verbose_name_plural': '訂單明細',
            },
        ),
        migrations.CreateModel(
            name='PurchaseApplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='單價金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='api.product', verbose_name='商品')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaseorder', verbose_name='採購單')),
            ],
            options={
                'verbose_name': '採購明細',
                'verbose_name_plural': '採購明細',
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_quantity', models.PositiveIntegerField(verbose_name='批次進貨數量')),
                ('remaining_quantity', models.PositiveIntegerField(verbose_name='剩餘數量')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='單位成本')),
                ('received_date', models.DateField(verbose_name='進貨日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='api.product', verbose_name='商品')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='api.purchaseapplyitem', verbose_name='採購明細')),
            ],
            options={
                'verbose_name': '庫存批次',
                'verbose_name_plural': '庫存批次',
                'ordering': ['received_date', 'id'],
            },
        ),
    ]
