# Generated by Django 6.0.3 on 2026-04-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_default_account_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='安全庫存量'),
        ),
    ]
