# Generated by Django 6.0.3 on 2026-04-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_safety_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客戶名稱')),
                ('contact_name', models.CharField(blank=True, default='', max_length=100, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='電話')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='供應商名稱')),
                ('contact_name', models.CharField(blank=True, default='', max_length=100, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='電話')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商',
                'ordering': ['name'],
            },
        ),
    ]
