# Generated by Django 6.0.3 on 2026-04-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.customer', verbose_name='客戶'),
        ),
    ]
