# Generated by Django 6.0.3 on 2026-04-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_customer_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='已入帳'),
        ),
    ]
