# Generated by Django 6.0.3 on 2026-04-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_set_existing_vouchers_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(default='個', max_length=20, verbose_name='基本單位'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='最新成本'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.supplier', verbose_name='供應商'),
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='包裝名稱')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='包含基本單位數量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='包裝售價')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='包裝成本')),
                ('barcode', models.CharField(blank=True, default='', max_length=64, verbose_name='條碼')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設包裝')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='api.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品包裝',
                'verbose_name_plural': '商品包裝',
                'ordering': ['quantity'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.productpackaging', verbose_name='包裝'),
        ),
        migrations.AddField(
            model_name='purchaseapplyitem',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='api.productpackaging', verbose_name='包裝'),
        ),
    ]
