# Generated by Django 6.0.3 on 2026-04-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_backfill_product_packagings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpackaging',
            options={'ordering': ['quantity', 'id'], 'verbose_name': '商品包裝', 'verbose_name_plural': '商品包裝'},
        ),
        migrations.AlterField(
            model_name='purchaseapplyitem',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='每包裝單價'),
        ),
    ]
