# Generated by Django 6.0.3 on 2026-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='單位成本'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='售價'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='目前售價'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='最新成本'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='包裝成本'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='包裝售價'),
        ),
        migrations.AlterField(
            model_name='purchaseapplyitem',
            name='fee',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='每包裝單價'),
        ),
    ]
