# Generated by Django 6.0.3 on 2026-04-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_inventorybatch_unit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='實盤數量')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_counts', to='api.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '盤點草稿',
                'verbose_name_plural': '盤點草稿',
                'unique_together': {('product',)},
            },
        ),
    ]
